# -*- coding: utf-8 -*-
"""DTI-Predictor-with-ADMET-Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10ynKW5Ad6J_ShsQ-kbR_2YQOXuDppSLs

**Install Libraries & Load Dataset**
"""

# Install required libraries
!pip install PyTDC

# Import dataset loader
from tdc.multi_pred import DTI

# Load BindingDB dataset (drug-target interactions)
data = DTI(name='BindingDB_Kd')

# Handle duplicate values (keep best binding)
data.harmonize_affinities(mode='max_affinity')

# Convert to dataframe
df = data.get_data()

# Convert binding value → classification
# If binding strength < 1000 → interaction (1), else no interaction (0)
threshold = 1000
df['interaction'] = df['Y'].apply(lambda x: 1 if x < threshold else 0)

# Keep only required columns
df = df[['Drug','Target','interaction']]

# Use smaller sample for faster training
df = df.sample(2000, random_state=42)

print(df.head())

"""**Convert Drug (SMILES → Fingerprint)**"""

# Install RDKit (for chemistry processing)
!pip install rdkit

from rdkit import Chem
from rdkit.Chem import AllChem
import torch

# Function: Convert SMILES → numerical vector
def smiles_to_fp(smiles):

    # Convert SMILES to molecule
    mol = Chem.MolFromSmiles(smiles)
    # Skip invalid molecules
    if mol is None:
        return None

    # Morgan fingerprint (1024 features)
    fp = AllChem.GetMorganFingerprintAsBitVect(mol, 2, nBits=1024)
    return torch.tensor(list(fp), dtype=torch.float)

"""**Convert Protein (Sequence → Numbers)**"""

import numpy as np

# List of amino acids
amino_acids = list("ACDEFGHIKLMNPQRSTVWY")
# Map each amino acid → number
aa_dict = {aa:i for i,aa in enumerate(amino_acids)}

# Maximum protein length
max_len = 512

# Function: Encode protein sequence
def encode_protein(seq):

    # Convert letters → numbers
    arr = [aa_dict.get(a,0) for a in seq[:max_len]]

    # Pad sequence if shorter than max_len
    if len(arr) < max_len:
        arr += [0]*(max_len - len(arr))

    return torch.tensor(arr, dtype=torch.long)

"""**Attention Layer**"""

import torch.nn as nn

# This layer learns which parts of protein are important
class Attention(nn.Module):

    def __init__(self, dim):
        super().__init__()

        self.fc = nn.Linear(dim,1)

    def forward(self,x):
        # x is expected to be (sequence_length, batch_size, embedding_dim)
        # self.fc(x) will be (sequence_length, batch_size, 1)
        weights = torch.softmax(self.fc(x), dim=0) # Apply softmax over sequence length dimension
        # (weights * x) will be (sequence_length, batch_size, embedding_dim)
        output = (weights * x).sum(dim=0) # Sum over sequence length dimension
        # output will be (batch_size, embedding_dim)
        return output, weights

"""**Build Deep Learning Model**"""

class Final_DTI_Model(nn.Module):

    def __init__(self):
        super().__init__()

        # Drug processing (fingerprint → features)
        self.drug_fc = nn.Linear(1024,256)

        # Protein embedding (like word embedding)
        self.embed = nn.Embedding(20,128)

        # Transformer encoder (learn sequence patterns)
        encoder_layer = nn.TransformerEncoderLayer(d_model=128, nhead=4)
        self.transformer = nn.TransformerEncoder(encoder_layer, num_layers=2)

        # Attention layer
        self.attn = Attention(128)

        # Final classification layers
        self.fc1 = nn.Linear(256+128,128)
        self.fc2 = nn.Linear(128,1)

        self.relu = nn.ReLU()
        self.sigmoid = nn.Sigmoid()

    def forward(self, drug, protein):

        # Drug feature extraction
        d = self.relu(self.drug_fc(drug))

        # Protein processing
        p = self.embed(protein).unsqueeze(1)
        p = self.transformer(p)

        # Apply attention
        p, attn_weights = self.attn(p)

        # Combine drug + protein features
        combined = torch.cat((d, p.squeeze()), dim=0)

        # Final prediction
        out = self.relu(self.fc1(combined))
        out = self.sigmoid(self.fc2(out))

        return out, attn_weights

"""**Prepare Dataset**"""

dataset = []

for _,row in df.iterrows():

    # Convert drug and protein
    d = smiles_to_fp(row['Drug'])
    p = encode_protein(row['Target'])

    # Skip invalid drugs
    if d is not None:
        dataset.append((d,p,row['interaction']))

print("Dataset size:", len(dataset))

from sklearn.model_selection import train_test_split

# Proper train-test split (VERY IMPORTANT)
train_data, test_data = train_test_split(dataset, test_size=0.2, random_state=42)

print("Train size:", len(train_data))
print("Test size:", len(test_data))

"""**Train Model**"""

model = Final_DTI_Model()

criterion = nn.BCELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

losses = [] # Initialize losses list

# Train for few epochs
for epoch in range(5):

    total_loss = 0

    for d,p,label in train_data:

        optimizer.zero_grad()

        pred,_ = model(d,p)


        loss = criterion(pred, torch.tensor([label], dtype=torch.float))

        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    losses.append(total_loss) # Append total_loss for the epoch
    print("Epoch:", epoch+1, "Loss:", total_loss)

import matplotlib.pyplot as plt

plt.plot(losses)
plt.title("Training Loss Curve")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.show()

"""**Model Evaluation**"""

from sklearn.metrics import accuracy_score, f1_score, roc_auc_score, average_precision_score

y_true, y_pred, y_prob = [], [], []

# Test on unseen data
for d,p,label in dataset[500:800]:

    pred,_ = model(d,p)
    prob = pred.item()

    y_true.append(label)
    y_prob.append(prob)
    y_pred.append(1 if prob > 0.5 else 0)

# Print metrics
print("Accuracy:", accuracy_score(y_true,y_pred))
print("F1 Score:", f1_score(y_true,y_pred))
print("ROC-AUC:", roc_auc_score(y_true,y_prob))
print("PR-AUC:", average_precision_score(y_true,y_prob))

"""**ROC Curve**"""

!pip install matplotlib

import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc

fpr, tpr, _ = roc_curve(y_true, y_prob)
roc_auc = auc(fpr, tpr)

plt.figure()
plt.plot(fpr, tpr, label="ROC AUC = %0.2f" % roc_auc)
plt.plot([0,1],[0,1],'--')

plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.legend()

plt.show()

"""**PR Curve**"""

from sklearn.metrics import precision_recall_curve

precision, recall, _ = precision_recall_curve(y_true, y_prob)

plt.figure()
plt.plot(recall, precision)

plt.xlabel("Recall")
plt.ylabel("Precision")
plt.title("Precision-Recall Curve")

plt.show()

"""**Prediction 1**"""

# IMPORTS
from rdkit import Chem
from rdkit.Chem import AllChem, Descriptors, Draw
from rdkit.DataStructs import TanimotoSimilarity
from IPython.display import display
import torch

# ADMET FUNCTION

def admet_profile(smiles):
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        print("Invalid molecule")
        return

    print("\n🔷 ADMET PROFILING REPORT")

    mw = Descriptors.MolWt(mol)
    logp = Descriptors.MolLogP(mol)
    h_donors = Descriptors.NumHDonors(mol)
    h_acceptors = Descriptors.NumHAcceptors(mol)

    print("\n👉 Lipinski Rule Check:")
    print("Molecular Weight:", round(mw,2))
    print("LogP:", round(logp,2))
    print("H Donors:", h_donors)
    print("H Acceptors:", h_acceptors)

    if mw < 500 and logp < 5 and h_donors <= 5 and h_acceptors <= 10:
        print("✅ Drug-Like Molecule")
    else:
        print("❌ May have poor drug-likeness")

    print("\n👉 Blood-Brain Barrier (BBB):")
    if logp > 2:
        print("🧠 Likely to cross BBB")
    else:
        print("🚫 Unlikely to cross BBB")

    print("\n👉 Toxicity (Heuristic):")
    if mw > 600:
        print("⚠️ Higher toxicity risk")
    else:
        print("✅ Lower toxicity risk")


# MOLECULE VISUALIZATION

def visualize_atoms(smiles):
    mol = Chem.MolFromSmiles(smiles)
    return Draw.MolToImage(mol)


# SIMILARITY SEARCH

def find_similar_drugs(query_smiles, df, top_n=5):

    query_mol = Chem.MolFromSmiles(query_smiles)
    query_fp = AllChem.GetMorganFingerprintAsBitVect(query_mol, 2, nBits=1024)

    similarities = []

    for sm in df['Drug'].head(100):

        mol = Chem.MolFromSmiles(sm)
        if mol is None:
            continue

        fp = AllChem.GetMorganFingerprintAsBitVect(mol, 2, nBits=1024)
        sim = TanimotoSimilarity(query_fp, fp)

        similarities.append((sm, sim, mol))

    similarities.sort(key=lambda x: x[1], reverse=True)
    top_results = similarities[:top_n]

    print("\n🔷 TOP SIMILAR DRUGS\n")

    mols = []

    for i, (sm, score, mol) in enumerate(top_results):

        print(f"🔹 Drug {i+1}")
        print("SMILES:", sm)
        print("Similarity Score:", round(score, 3))

        display(Draw.MolToImage(mol, size=(250,250)))
        mols.append(mol)

    print("\n🔷 GRID VIEW (ALL DRUGS)\n")

    grid_img = Draw.MolsToGridImage(mols, molsPerRow=top_n, subImgSize=(200,200))
    display(grid_img)

    return top_results


# FINAL PIPELINE FUNCTION

def full_drug_analysis(smiles, protein_seq, df):

    # Convert inputs
    d = smiles_to_fp(smiles)
    p = encode_protein(protein_seq)

    # Prediction
    pred, _ = model(d, p)
    prob = pred.item()

    print("\n🔷 MODEL PREDICTION")
    print("Interaction Probability:", round(prob, 4))

    # Interpretation
    print("\n🔷 INTERPRETATION")

    if prob > 0.8:
        print("👉 Very high probability that the drug strongly binds to the protein.")
    elif prob > 0.6:
        print("👉 High probability of binding between drug and protein.")
    elif prob > 0.4:
        print("👉 Moderate interaction possible.")
    else:
        print("👉 Low probability — drug is unlikely to bind effectively.")

    print(f"\nThis value ({round(prob,3)}) shows likelihood of interaction.")

    # ADMET
    admet_profile(smiles)

    # Visualization
    print("\n🔷 MOLECULE STRUCTURE\n")
    img = visualize_atoms(smiles)
    display(img)

    # Similar drugs
    similar = find_similar_drugs(smiles, df)

    return similar


# RUN EVERYTHING

full_drug_analysis(
    smiles="CCO",
    protein_seq="MAHVRGLQLPGCLALAALCSLVH",
    df=df
)

"""**Prediction 2**"""

# IMPORTS
from rdkit import Chem
from rdkit.Chem import AllChem, Descriptors, Draw
from rdkit.DataStructs import TanimotoSimilarity
from IPython.display import display
import torch

# ADMET FUNCTION

def admet_profile(smiles):
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        print("Invalid molecule")
        return

    print("\n🔷 ADMET PROFILING REPORT")

    mw = Descriptors.MolWt(mol)
    logp = Descriptors.MolLogP(mol)
    h_donors = Descriptors.NumHDonors(mol)
    h_acceptors = Descriptors.NumHAcceptors(mol)

    print("\n👉 Lipinski Rule Check:")
    print("Molecular Weight:", round(mw,2))
    print("LogP:", round(logp,2))
    print("H Donors:", h_donors)
    print("H Acceptors:", h_acceptors)

    if mw < 500 and logp < 5 and h_donors <= 5 and h_acceptors <= 10:
        print("✅ Drug-Like Molecule")
    else:
        print("❌ May have poor drug-likeness")

    print("\n👉 Blood-Brain Barrier (BBB):")
    if logp > 2:
        print("🧠 Likely to cross BBB")
    else:
        print("🚫 Unlikely to cross BBB")

    print("\n👉 Toxicity (Heuristic):")
    if mw > 600:
        print("⚠️ Higher toxicity risk")
    else:
        print("✅ Lower toxicity risk")


# MOLECULE VISUALIZATION

def visualize_atoms(smiles):
    mol = Chem.MolFromSmiles(smiles)
    return Draw.MolToImage(mol)


# SIMILARITY SEARCH

def find_similar_drugs(query_smiles, df, top_n=5):

    query_mol = Chem.MolFromSmiles(query_smiles)
    query_fp = AllChem.GetMorganFingerprintAsBitVect(query_mol, 2, nBits=1024)

    similarities = []

    for sm in df['Drug'].head(100):

        mol = Chem.MolFromSmiles(sm)
        if mol is None:
            continue

        fp = AllChem.GetMorganFingerprintAsBitVect(mol, 2, nBits=1024)
        sim = TanimotoSimilarity(query_fp, fp)

        similarities.append((sm, sim, mol))

    similarities.sort(key=lambda x: x[1], reverse=True)
    top_results = similarities[:top_n]

    print("\n🔷 TOP SIMILAR DRUGS\n")

    mols = []

    for i, (sm, score, mol) in enumerate(top_results):

        print(f"🔹 Drug {i+1}")
        print("SMILES:", sm)
        print("Similarity Score:", round(score, 3))

        display(Draw.MolToImage(mol, size=(250,250)))
        mols.append(mol)

    print("\n🔷 GRID VIEW (ALL DRUGS)\n")

    grid_img = Draw.MolsToGridImage(mols, molsPerRow=top_n, subImgSize=(200,200))
    display(grid_img)

    return top_results


# FINAL PIPELINE FUNCTION

def full_drug_analysis(smiles, protein_seq, df):

    # Convert inputs
    d = smiles_to_fp(smiles)
    p = encode_protein(protein_seq)

    # Prediction
    pred, _ = model(d, p)
    prob = pred.item()

    print("\n🔷 MODEL PREDICTION")
    print("Interaction Probability:", round(prob, 4))

    # Interpretation
    print("\n🔷 INTERPRETATION")

    if prob > 0.8:
        print("👉 Very high probability that the drug strongly binds to the protein.")
    elif prob > 0.6:
        print("👉 High probability of binding between drug and protein.")
    elif prob > 0.4:
        print("👉 Moderate interaction possible.")
    else:
        print("👉 Low probability — drug is unlikely to bind effectively.")

    print(f"\nThis value ({round(prob,3)}) shows likelihood of interaction.")

    # ADMET
    admet_profile(smiles)

    # Visualization
    print("\n🔷 MOLECULE STRUCTURE\n")
    img = visualize_atoms(smiles)
    display(img)

    # Similar drugs
    similar = find_similar_drugs(smiles, df)

    return similar


# RUN EVERYTHING

full_drug_analysis(
    smiles="CC(=O)OC1=CC=CC=C1C(=O)O",
    protein_seq="MDSKGSSQKGSRLLLLLVVSNLLLCQGVVSTPVQL",
    df=df
)

